const rawData = {
  easy: [
    { word: "CRIME", clue: "Illegal act punishable by law" },
    { word: "CRIMINAL", clue: "Person who commits a crime" },
    { word: "JAIL", clue: "Place where accused are kept" },
    { word: "WITNESS", clue: "Person who saw a crime happen" },
    { word: "CLUE", clue: "Piece of evidence that helps solve a case" },
    { word: "THEFT", clue: "Taking property without permission" },
    { word: "MURDER", clue: "Killing a person intentionally" },
    { word: "POLICE", clue: "Government force that enforces law" },
    { word: "VERDICT", clue: "Final decision given by a court" },
    { word: "BURGLARY", clue: "Entering a house illegally to steal" },
    { word: "SUSPECT", clue: "Person suspected of a crime" },
    { word: "PRINT", clue: "Unique mark left by a finger" },
    { word: "SENTENCE", clue: "Legal punishment given by a judge" },
    { word: "ROBBERY", clue: "Taking property using force" },
    { word: "STATUTE", clue: "Written law passed by authority" },
    { word: "VICTIM", clue: "Person harmed by a crime" },
    { word: "JUSTICE", clue: "Fair treatment under law" },
    { word: "COURT", clue: "Place where legal cases are heard" },
    { word: "FORENSIC", clue: "Science used to investigate crimes" },
    { word: "LAWYER", clue: "Person who argues a case in court" }
  ],
  medium: [
    { word: "CRIMINOLOGY", clue: "Study of crime and criminal behavior" },
    { word: "AUTOPSY", clue: "Medical examination of a dead body" },
    { word: "RIGOR", clue: "Stiffening of muscles after death" },
    { word: "DECAY", clue: "Breakdown of a body after death" },
    { word: "SPLATTER", clue: "Study of blood stain patterns" },
    { word: "TOXICOLOGY", clue: "Science of analyzing drugs and poisons" },
    { word: "GRAPHOLOGY", clue: "Study of handwriting for identification" },
    { word: "FIBER", clue: "Small thread-like trace evidence" },
    { word: "GSR", clue: "Gunshot residue test material" },
    { word: "GENETICS", clue: "Study of genes for identification" },
    { word: "PERJURY", clue: "Giving false statement under oath" },
    { word: "FORENSICS", clue: "Crime scene investigation work" },
    { word: "TRESPASS", clue: "Entering property without permission" },
    { word: "TOXIN", clue: "Poisonous chemical substance" },
    { word: "OSTEOLOGY", clue: "Scientific study of bones" },
    { word: "FRAUD", clue: "Crime of financial deception" },
    { word: "CYBERCRIME", clue: "Crime committed using computers" },
    { word: "EXHIBIT", clue: "Object presented as court evidence" },
    { word: "INSPECTOR", clue: "Police officer rank above sub-inspector" },
    { word: "RESIDUE", clue: "Chemical trace left after explosion" }
  ],
  hard: [
    { word: "ENTOMOLOGY", clue: "Study of insects on dead bodies" },
    { word: "TRIGONOMETRY", clue: "Math used to calculate blood angles" },
    { word: "CRANIOMETRY", clue: "Measurement of skull features" },
    { word: "ARSON", clue: "Investigation of fire-related crimes" },
    { word: "BALLISTICS", clue: "Science of bullets and firearms" },
    { word: "TOXICOLOGY", clue: "Study of toxic substances" },
    { word: "QUESTIONED", clue: "Analysis of disputed documents" },
    { word: "PHONETICS", clue: "Study of speech sounds in voice analysis" },
    { word: "LIVOR", clue: "Blood pooling after death" },
    { word: "OSTEOLOGY", clue: "Scientific study of bones" },
    { word: "PCR", clue: "DNA copying method" },
    { word: "ODONTOLOGY", clue: "Study of bite marks for identification" },
    { word: "NINHYDRIN", clue: "Chemical used to reveal fingerprints" },
    { word: "TRAJECTORY", clue: "Path followed by a bullet" },
    { word: "FACIAL", clue: "Rebuilding a face from a skull" },
    { word: "PLASMA", clue: "Liquid part of blood" },
    { word: "RECONSTRUCT", clue: "Rebuilding sequence of a crime" },
    { word: "CONTAMINATE", clue: "Mixing that damages evidence" },
    { word: "INSANITY", clue: "Legal defense of unsound mind" },
    { word: "PROFILING", clue: "Analysis of criminal behavior patterns" }
  ],
  pro: [
    { word: "ALGORMORTIS", clue: "Body cooling after death" },
    { word: "LIVORMORTIS", clue: "Blood settling after death" },
    { word: "RIGORMORTIS", clue: "Muscle stiffening after death" },
    { word: "PROFILING", clue: "DNA-based identification method" },
    { word: "TRICHOLOGY", clue: "Scientific study of hair" },
    { word: "PEDOLOGY", clue: "Study of soil in forensics" },
    { word: "TEXTILES", clue: "Study of textile fibers" },
    { word: "NARCOTICS", clue: "Laws regulating illegal drugs" },
    { word: "WHORL", clue: "Circular fingerprint pattern" },
    { word: "LOOP", clue: "Fingerprint pattern with curved ridges" },
    { word: "ARCH", clue: "Fingerprint pattern forming arch shape" },
    { word: "CYBERFORENSICS", clue: "Digital evidence investigation field" },
    { word: "MAPPING", clue: "Measuring and documenting crime scene" },
    { word: "ENTRY", clue: "Wound where a bullet enters the body" },
    { word: "EXIT", clue: "Wound where a bullet exits the body" },
    { word: "CUSTODY", clue: "Record of evidence handling" },
    { word: "BALLISTICS", clue: "Study of firearms in forensics" },
    { word: "CHLORINE", clue: "Green toxic gas used in chemical exposure" },
    { word: "LIABILITY", clue: "Legal responsibility for damage" },
    { word: "INTENT", clue: "Purpose behind committing a crime" }
  ]
};

export default rawData;
